# Generated by Django 5.1.5 on 2025-03-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
