# Generated by Django 5.1.5 on 2025-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
