# Generated by Django 5.1.5 on 2025-03-29 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_invite_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField()),
                ('text', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Dica',
                'verbose_name_plural': 'Dicas',
                'db_table': 'tips',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tip_of_day',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.tip'),
        ),
    ]
