# Generated by Django 5.1.5 on 2025-04-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tip_user_tip_of_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LOGIN', 'LOGIN'), ('LOGOUT', 'LOGOUT'), ('FEEDBACK', 'FEEDBACK')], default='LOGIN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'db_table': 'actions',
            },
        ),
    ]
