# Generated by Django 5.1.5 on 2025-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='ip',
            field=models.GenericIPAddressField(default='Casa com quinta ou área externa'),
            preserve_default=False,
        ),
    ]
