# Generated by Django 5.1.5 on 2025-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_feedback_user_alter_invite_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
