# Generated by Django 5.1.5 on 2025-03-11 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetAge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specie', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('human_age_in_years', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PetPrevention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specie', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200, null=True)),
                ('feature', models.CharField(max_length=200, null=True)),
                ('action', models.CharField(max_length=1000)),
                ('motive', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PetRace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('specie', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetMinMaxWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200, null=True)),
                ('min_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petrace')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('specie', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('is_castrated', models.BooleanField()),
                ('color', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('activity', models.CharField(max_length=200)),
                ('health_problem', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('predominant_race', models.CharField(max_length=200, null=True)),
                ('coat', models.CharField(max_length=200, null=True)),
                ('coat_texture', models.CharField(max_length=200, null=True)),
                ('coat_pattern', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.petrace')),
            ],
        ),
    ]
