# Generated by Django 5.1.5 on 2025-01-29 00:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('health_problem', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('predominant_race', models.CharField(max_length=200, null=True)),
                ('coat', models.CharField(max_length=200, null=True)),
                ('coat_texture', models.CharField(max_length=200, null=True)),
                ('coat_pattern', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField()),
                ('weight', models.IntegerField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
