# Generated by Django 5.1.5 on 2025-03-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.ForeignKey(default='48f76a94-0028-4fe9-8748-db7a24172624', on_delete=django.db.models.deletion.CASCADE, to='pets.petrace'),
            preserve_default=False,
        ),
    ]
