# Generated by Django 5.1.5 on 2025-04-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='habitation',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Área rural (sítio, fazenda ou chácara)', 'Área rural (sítio, fazenda ou chácara'), ('Casa sem quintal', 'Casa sem quintal'), ('Casa com quintal ou área externa', 'Casa com quinta ou área externa'), ('Outro', 'Outro')], default='Casa com quinta ou área externa', max_length=40),
            preserve_default=False,
        ),
    ]
