# Generated by Django 5.1.5 on 2025-01-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
