# Generated by Django 5.1.5 on 2025-02-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='tutor',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_castrated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='FEMALE', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='specie',
            field=models.CharField(default='DOG', max_length=200),
            preserve_default=False,
        ),
    ]
