# Generated by Django 5.1.5 on 2025-02-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
