# Generated by Django 5.1.5 on 2025-02-21 08:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_pet_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetRace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("specie", models.CharField(max_length=200)),
                ("size", models.CharField(max_length=200, null=True)),
                ("min_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_weight", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
