# Generated by Django 5.1.5 on 2025-04-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField()),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai.recommendation')),
            ],
        ),
    ]
