# Generated by Django 5.1.5 on 2025-04-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='recommendation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai.recommendation'),
        ),
    ]
